# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"
    propagate_case: true
    # word: true
    # uppercase_style: "capitalize_words"
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!
      
  - trigger: ":br"
    replace: "Best Regards,\nAshish Kushwaha"
  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    word: true
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # - trigger: ":ts"
  #   replace: "{{mydate}},{{mytime}}"
  #   vars:
  #     - name: mydate
  #       type: date
  #       params:
  #         format: "%dddd/%MMMM D/%YYYY"
  #     - name: mytime
  #       type: date
  #       params:
  #         format: "%_H:%M:%S"

  # - trigger: ":day"
  #   replace: "{{now:DD}}"
  #   vars:
  #     - name: now
  #       type: date
  #       params:
  #         format: "DD"

  - trigger: ":time"
    replace: "{{mytime}}"
    word: true
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

  - trigger: ":tomorrow"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%x"
          offset: 86400 # the number of seconds to be added to the current time when expanding a match. 


  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more!
  # For more information,
  #   - trigger: ":now"
    # replace: "It's {{mytime}}"
    # vars:
    #   - name: mytime
    #     type: date
    #     params:
    #       format: "%H:%M"

    # Courcer Hint
    #   - trigger: ":div"
    #    replace: "<div>$|$</div>"


    #    Match Disambiguation
    #  all three matches share the same trigger. 
    #  If you now type :quote, Espanso will display a
    #  selection dialog to let you choose the desired one:
    # - trigger: ":quote"
    #   replace: "Every moment is a fresh beginning."
    # - trigger: ":quote"
    #   replace: "Everything you can imagine is real."
    # - trigger: ":quote"
    #   replace: "Whatever you do, do it well."
  
    # Choide Extension
    # letting you choose the right value from a list.
    #   - trigger: ":quote"
    #     replace: "{{output}}"
    #     vars:
    #       - name: output
    #         type: choice
    #         params:
    #           values:
    #             - "Every moment is a fresh beginning."
    #             - "Everything you can imagine is real."
    #             - "Whatever you do, do it well."

    # Randomly auto selection
    # will choose a random one, useful to avoid repetitions.
    # - trigger: ":quote"
    # replace: "{{output}}"
    # vars:
    #   - name: output
    #     type: random
    #     params:
    #       choices:
    #         - "Every moment is a fresh beginning."
    #         - "Everything you can imagine is real."
    #         - "Whatever you do, do it well."
    # Search Labels 
    #   - trigger: ":tomorrow"
    #   replace: "{{mytime}}"
    #   label: "Insert tomorrow's date, such as 5-Jan-2022"
    #   vars:
    #     - name: mytime
    #       type: date
    #       params:
    #         format: "%v"
    #         offset: 86400
  
    # - trigger: ":yesterday"
    #   replace: "{{mytime}}"
    #   label: "Insert yesterday's date, such as 5-Jan-2022"
    #   vars:
    #     - name: mytime
    #       type: date
    #       params:
    #         format: "%v"
    #         offset: -86400

    # Multiple Triggers   
    #  - triggers: ["hello", "hi"]
    #   replace: "world"
    #
    # inserting image
    #   - trigger: ":cat"
    #     image_path: "$CONFIG/images/cat.png"
    
    # clipboard extension
    # enables to include the current clipboard content in a match
    #   - trigger: ":a"
    #   replace: "<a href='{{clipboard}}' />$|$</a>"
    #   vars:
    #     - name: "clipboard"
    #       type: "clipboard"
    
    # script extension
    # enables you to call an external script,
    # written in any language, and use its output in a match.
    # - trigger: ":pyscript"
    #     replace: "{{output}}"
    #       vars:
    #         - name: output
    #          type: script
    #           params:
    #            args:
    #               - python
    #               - /path/to/your/script.py
    #
    
    # Shell extension
    # enable to execute shell commands
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"
          debug: true

