# Location of present dotfile folder cloned grom git
myloc="$(dirname $(realpath ${BASH_SOURCE[@]:-0}))" 

# function to link the files
linking() {
	echo "$1 -> $2"
	ln -sf "$1" "$2"
}

 linking "$myloc/shell" "$HOME/.config/shell"
 linking "$myloc/starship.toml" "$HOME/.config/starship.toml"
 linking "$myloc/.vimrc" "$HOME/"
 linking "$myloc/tmux" "$HOME/.config/tmux"
 linking "$myloc/foot" "$HOME/.config/foot"



unset linking
echo " DONE"
